ARM: OMAP4: Move pm44xx_errata out of #define
When ARCH_OMAP4 is not set resolve compiler errors
arch/arm/mach-omap2/omap-wakeupgen.c: In function 'omap_wakeupgen_init':
arch/arm/mach-omap2/omap-wakeupgen.c:587: error: 'pm44xx_errata' undeclared (first use in this function)
arch/arm/mach-omap2/omap-wakeupgen.c:587: error: (Each undeclared identifier is reported only once
arch/arm/mach-omap2/omap-wakeupgen.c:587: error: for each function it appears in.)

arch/arm/mach-omap2/omap-smp.c: In function 'wakeup_secondary':
arch/arm/mach-omap2/omap-smp.c:187: error: 'pm44xx_errata' undeclared (first use in this function)
arch/arm/mach-omap2/omap-smp.c:187: error: (Each undeclared identifier is reported only once
arch/arm/mach-omap2/omap-smp.c:187: error: for each function it appears in.)

Since the variable pm44xx_errata is used in run time code it should be available to all kernel configs

Change-Id: I08bb3e902d7747ee7183afd9dfac2ef0426ff2d5
Reported-by: Vince Kim <vince.kim@ti.com>
Signed-off-by: Dan Murphy <dmurphy@ti.com>