ARM: Ensure armv7 compiles with newer GCC compiler version
This patch fixes the below compilation error observed with GCC 4.6

arch/arm/mm/proc-v7.S: Assembler messages:
arch/arm/mm/proc-v7.S:260: Error: selected processor does not support ARM mode `smc #0'
arch/arm/mm/proc-v7.S:260: Error: selected processor does not support ARM mode `smc #0'

Similar to
commit fe297dde5ae8f8bf67d3a87759289a99b48ecb2c
Author: John Rigby <john.rigby@linaro.org>
OMAP4: enable smc instruction in new assembler versions

Change-Id: I3f4499591c82678fe88e96d2fcc6c384acf7e3e8
Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>