usb: dwc3: Fix compilation break
This patch fixes a bad merge conflict that caused
following compilation break:

drivers/usb/dwc3/gadget.c:1431: error: conflicting types for 'dwc3_gadget_run_stop'
drivers/usb/dwc3/gadget.h:128: note: previous declaration of 'dwc3_gadget_run_stop' was here
drivers/usb/dwc3/gadget.c: In function 'dwc3_gadget_pullup':
drivers/usb/dwc3/gadget.c:1491: error: redeclaration of 'ret' with no linkage
drivers/usb/dwc3/gadget.c:1488: note: previous definition of 'ret' was here
make[3]: *** [drivers/usb/dwc3/gadget.o] Error 1

This patch should have been a part of:

7a2dea3800fee2bcb54dce2739ae02b0f2e15c11
usb: dwc3: return error in case of run/stop timeout

Change-Id: I1335a937881b5995ff273b4d8520953ac6028359
Signed-off-by: Moiz Sonasath <m-sonasath@ti.com>