Revert "HACK: DRA7xx: usb: dwc3: set mailbox in gadget pullup."
This reverts commit 7876130d20362defe551e4729c2348f666c801be.

Reason: dependency hack is removed too
commit: a2f03cba4edfb8837f882e967a01663d70686fee
Revert "HACK: usb: dwc3: dwc3 wrapper update for multiple usb subsystems"

without this we will see the following compilation error due to
the change in "dwc3_omap_mailbox" structure

error:
drivers/usb/dwc3/gadget.c: In function 'dwc3_gadget_pullup':
drivers/usb/dwc3/gadget.c:1466:3: error: incompatible type for argument 1 of 'dwc3_omap_mailbox'
include/linux/usb/dwc3-omap.h:22:12: note: expected 'enum omap_dwc3_vbus_id_status' but argument is of type 'struct device *'
drivers/usb/dwc3/gadget.c:1466:3: error: too many arguments to function 'dwc3_omap_mailbox'

Note: android platform device tree also needs to update fstab
to make usb mass storage functional.

Change-Id: I174f92ed1d4c86addabe5e1fa27016316c243005
Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>