OMAP4: DSS: Fix checkpatch error in panel-tc358765
this patch is to fix checkpatch errors

ERROR: space prohibited after that open parenthesis '('
ERROR: space prohibited before that close parenthesis ')'
at FILE: drivers/video/omap2/displays/panel-tc358765.c:472:
if ( unlikely(!timings) ) {

caused by
commit 28148bcfa0f34812ce52f83cc280758a263ea291
Author: Tomi Valkeinen <tomi.valkeinen@ti.com>
OMAP4: DSS: Add panel for Tablet boards
--
Change-Id: I899b32388961b65433a6e38f705ff8b24e5f2fac
Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>