defconfig: omap2plus: Enable Switch class support
Enable GPIO Switch class support.

HDMI hpd in Android Kernel uses Switch class.

We see the following error if switch class support is not enabled

drivers/built-in.o: In function `hdmi_hotplug_detect_worker':
drivers/video/omap2/dss/hdmi_panel.c:555: undefined reference to `switch_set_state'
drivers/video/omap2/dss/hdmi_panel.c:505: undefined reference to `switch_set_state'
drivers/built-in.o: In function `hdmi_panel_init':
drivers/video/omap2/dss/hdmi_panel.c:740: undefined reference to `switch_dev_register'
drivers/video/omap2/dss/hdmi_panel.c:744: undefined reference to `switch_set_state'
drivers/video/omap2/dss/hdmi_panel.c:758: undefined reference to `switch_dev_unregister'
drivers/built-in.o: In function `hdmi_panel_exit':
drivers/video/omap2/dss/hdmi_panel.c:768: undefined reference to `switch_dev_unregister'

correct fix is to move the common hdmi code and drivers/switch to p-ti-linux-3.8.y and
enable switch class support there too.{Since this driver is already upstreamed}

Change-Id: I289a3dac0b81f51af0fb0d44639ef85b7cd8cd11
Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>