OMAP3: Fix compilation error in board-zoom2
This patch fixes this compilation error:
arch/arm/mach-omap2/board-zoom2.c:84: error:
implicit declaration of function 'zoom_display_init'

The error was introduced due to commit:
f36c5988203884097b902eda8fb5c2e603743273

Change-Id: I65ef65b7e3b84e44f284a2a1c69fdc0a2344b38f
Signed-off-by: Christina Warren <cawarren@ti.com>