wl12xx: fix separate-object-folder builds
Make this go away (happens when building with a separate object
directory):

Assembler messages:
Fatal error: can't create drivers/net/wireless/wl12xx/.tmp_wl12xx_platform_data.o: No such file or directory
drivers/net/wireless/wl12xx/wl12xx_platform_data.c: In function 'wl12xx_get_platform_data':
drivers/net/wireless/wl12xx/wl12xx_platform_data.c:28: error: cannot open drivers/net/wireless/wl12xx/.tmp_wl12xx_platform_data.gcno
drivers/net/wireless/wl12xx/wl12xx_platform_data.c:28: confused by earlier errors, bailing out

Change-Id: I37e88a9a995eeb3222ec02fe654a737a99a2314f
Signed-off-by: John W. Linville <linville@tuxdriver.com>
Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Signed-off-by: Ohad Ben-Cohen <ohad@wizery.com>
[jeff.carlyle@motorola.com: cherry-picked from git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux-2.6.git commit d99bf6e707444af4df294f54a679f679018d7ec3]
Signed-off-by: Jeffrey Carlyle <jeff.carlyle@motorola.com>