rtc-twl: fix build break caused by twl_rtc_write_u8 function
omap linux build breaks with the following crash log:

drivers/rtc/rtc-twl.c: In function 'twl_rtc_probe':
drivers/rtc/rtc-twl.c:559: error: too few arguments to function 'twl_rtc_write_u8'

and that is due to below stable v3.4.12 patch:

commit 6093dd2f5a10b5a071aa623be7927a6421762adb
Author: Kevin Hilman <khilman@ti.com>
drivers/rtc/rtc-twl.c: ensure all interrupts are disabled during probe

correct way to fix is to update 'twl_rtc_write_u8' function
which was introduced by
commit da014d7350f4e95bb0999d98af51f81910e9f6d2
Author: Sebastien Guiriec <s-guiriec@ti.com>
RTC: palmas RTC support

Change-Id: I9e46789ff59350a9580539442cd41b47af0e3567
Signed-off-by: Huzefa Kankroliwala <huzefank@ti.com>
Signed-off-by: Praneeth Bajjuri <praneeth@ti.com>