switch: allow for non-android config builds
Compiling the android kernel non-android config, the build breaks
at the linker stage as follows:

This patch fixes this linker error for omap_4430sdp_defconfig compilation

  LD      init/built-in.o
  LD      .tmp_vmlinux1
sound/built-in.o: In function `twl6040_remove':
/git/android35/sound/soc/codecs/twl6040.c:1286: undefined reference to `switch_dev_unregister'
sound/built-in.o: In function `twl6040_probe':
/git/android35/sound/soc/codecs/twl6040.c:1207: undefined reference to `switch_dev_register'
/git/android35/sound/soc/codecs/twl6040.c:1265: undefined reference to `switch_dev_unregister'
sound/built-in.o: In function `twl6040_hs_jack_detect':
/git/android35/sound/soc/codecs/twl6040.c:1164: undefined reference to `switch_set_state'
sound/built-in.o: In function `twl6040_naudint_handler':
/git/android35/sound/soc/codecs/twl6040.c:438: undefined reference to `switch_set_state'
/git/android35/sound/soc/codecs/twl6040.c:447: undefined reference to `switch_set_state'
make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Vikram Pandita <vikram.pandita@ti.com>