ASoC: omap-abe-core: Call driver_deffered_probe_trigger only if built in
When audio is built as module we do not need to use deferred probe since the
fw file will be available right away, we do not need to wait for the FS.

Also fixes compillation error:
ERROR: "driver_deferred_probe_trigger" [sound/soc/omap/snd-soc-omap-abe.ko] undefined!

Signed-off-by: Peter Ujfalusi <peter.ujfalusi@ti.com>
Tested-by: Jyri Sarha <jsarha@ti.com>