usb: dwc3: Fix compile break
This patch fixes the following compilation error
introduced by the commit:

commit f46741d47965b0d421db2a2d5fc30f50a34b8731
usb: dwc3: gadget: disable U1/U2 on disconnect

drivers/usb/dwc3/gadget.c: In function 'dwc3_gadget_disconnect_interrupt':
drivers/usb/dwc3/gadget.c:1911: error: 'reg' undeclared (first use in this function)
drivers/usb/dwc3/gadget.c:1911: error: (Each undeclared identifier is reported only once
drivers/usb/dwc3/gadget.c:1911: error: for each function it appears in.)

Signed-off-by: Moiz Sonasath <m-sonasath@ti.com>
Signed-off-by: Felipe Balbi <balbi@ti.com>