arm/dts: dra7xx: Add CPSW and MDIO module nodes for dra7xx
Add CPSW and MDIO related device tree data for DRA7XX and made as status
disabled. Phy-id, pinmux for active and sleep state needs to be added in
board dts files and enable the CPSW device.

Change-Id: Ia8c6f8ec8eff0d66e0d05f4a6e1ce174a725b2fd
Signed-off-by: Mugunthan V N <mugunthanvnm@ti.com>
[Resolved merge conflict and rebased to 3.8 kernel]
Updated the CPSW and MDIO related device tree data with correct device
address offset and also to remove marco defines which caused compilation error
seen as below:
Error: arch/arm/boot/dts/dra7.dtsi:701.22-23 syntax error
FATAL ERROR: Unable to parse input tree
Signed-off-by: Praveen Rao <prao@ti.com>